apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"prometheus","meta.helm.sh/release-namespace":"prom","service.beta.kubernetes.io/linode-loadbalancer-nodebalancer-id":"ccm-default"},"creationTimestamp":"2024-08-01T15:30:59Z","labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"prometheus","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"prometheus","app.kubernetes.io/version":"v2.53.1","helm.sh/chart":"prometheus-25.24.1"},"name":"prometheus-server","namespace":"prom","resourceVersion":"309897","uid":"ac968fb6-465e-4744-a4ee-f5cef0e5264d"},"spec":{"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":9090,"protocol":"TCP","targetPort":9090}],"selector":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"prometheus","app.kubernetes.io/name":"prometheus"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prom
    service.beta.kubernetes.io/linode-loadbalancer-nodebalancer-id: ccm-default
  creationTimestamp: "2024-08-05T15:50:45Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.53.1
    helm.sh/chart: prometheus-25.24.1
  name: prometheus-server
  namespace: prom
  resourceVersion: "482839"
  uid: ff883ac8-55b6-4e3b-9bbf-60eedcf404e6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.128.156.179
  clusterIPs:
  - 10.128.156.179
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30829
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
