apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"ingress-nginx","meta.helm.sh/release-namespace":"kube-system"},"creationTimestamp":"2024-08-09T01:16:43Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/part-of":"ingress-nginx","app.kubernetes.io/version":"1.11.1","helm.sh/chart":"ingress-nginx-4.11.1"},"name":"ingress-nginx-controller","namespace":"kube-system","resourceVersion":"646606","uid":"4148a268-d7e3-4416-9695-934271db6103"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.128.109.80","clusterIPs":["10.128.109.80"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"prometheus-server","nodePort":31101,"port":9090,"protocol":"TCP","targetPort":9090},{"name":"web-app","nodePort":31100,"port":5000,"protocol":"TCP","targetPort":5000},{"appProtocol":"http","name":"http","nodePort":30097,"port":80,"protocol":"TCP","targetPort":"http"},{"appProtocol":"https","name":"https","nodePort":32719,"port":443,"protocol":"TCP","targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"hostname":"143-42-79-129.ip.linodeusercontent.com","ip":"143.42.79.129","ipMode":"VIP"}]}}}
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-08-09T01:16:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
    helm.sh/chart: ingress-nginx-4.11.1
  name: ingress-nginx-controller
  namespace: kube-system
  resourceVersion: "646648"
  uid: 4148a268-d7e3-4416-9695-934271db6103
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.128.109.80
  clusterIPs:
  - 10.128.109.80
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: prometheus-server
    nodePort: 31101
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: web-app
    nodePort: 31100
    port: 5000
    protocol: TCP
    targetPort: 5000
  - appProtocol: http
    name: http
    nodePort: 30097
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 32719
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: 143-42-79-129.ip.linodeusercontent.com
      ip: 143.42.79.129
      ipMode: VIP
