apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"prometheus","meta.helm.sh/release-namespace":"prom","service.beta.kubernetes.io/linode-loadbalancer-nodebalancer-id":"ccm-default","service.beta.kubernetes.io/linode-loadbalancer-throttle":"4"},"creationTimestamp":"2024-08-05T15:50:45Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"prometheus","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"prometheus","app.kubernetes.io/version":"v2.53.1","helm.sh/chart":"prometheus-25.24.1"},"name":"prometheus-server","namespace":"prom","resourceVersion":"501876","uid":"ff883ac8-55b6-4e3b-9bbf-60eedcf404e6"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.128.156.179","clusterIPs":["10.128.156.179"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","nodePort":30829,"port":9090,"protocol":"TCP","targetPort":9090}],"selector":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"prometheus","app.kubernetes.io/name":"prometheus"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"hostname":"139-144-127-243.ip.linodeusercontent.com","ip":"139.144.127.243","ipMode":"VIP"}]}}}
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prom
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.53.1
    helm.sh/chart: prometheus-25.24.1
  name: prometheus-server
  namespace: prom
spec:
  ports:
  - name: tcp-port
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
