apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app-service
  namespace: default
spec:
  ports:
  - name: tcp-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: web-app
  type: ClusterIP
